### ISSUE TITLE
Interior Design

### ISSUE THREAD

**Issue by noobLinda** [smeas/Beer-and-Plunder#103]
**Description**
Create sketches of the bars interior in Photoshop
such as the bar counter, bar area, entrance area etc
Example: What does the bar counter look like? What is behind the bar? bottles on shelf, skulls?
(look at subtasks)
We want every area to feel special and well thought out.

**Subtasks**
- [x] Bar counter
- [x] Bar area
- [x] Entrance area
- [x] Bear skin Rug/Carpet
- [x] Area for Hammer
- [x] Area for Axe
- [x] Area for Instrument

**Additional context**
Each subtask is completed when each sketch have been discussed and determined with the group
