### ISSUE TITLE
Minor Fixes - Models

### ISSUE THREAD

**Issue by denalice00** [smeas/Beer-and-Plunder#105]
**Description**
Fix the things listed below:

**Subtasks**
- [x] Make Wall Model repeatable
- [x] Fix gaps in mesh on Lowpoly Wall
- [x] Update Beertap FBX (make sure legs follow)
- [x] Fix Reversed Faces on Beertap, Twisty thing and Tankard

**Additional context**
Do these minor fixes to complete these assets,
