### ISSUE TITLE
Rework the music feature

### ISSUE THREAD

**Issue by DreamingJohnny** [smeas/Beer-and-Plunder#113]
**Description**
Vikings should wish for music the same way as they wish for beer. A viking that sits at the same table as one who has wished for music will also get a mood boost when the vikings desire for music is fullfilled.
Music is no longer an area of effect but directed at a viking.

**Subtasks**
- [x] Make the new desire "wishing for music"
- [x] Make it possible to have it be fullfilled by having someone play music for the viking
- [ ] Make it so other vikings sitting at the same table gets a mood boost when one viking gets it's desire for music fullfilled at the table.
- [x] Make it so that music as an action takes a small amount of time to perform.
