### ISSUE TITLE
Implement repairing tables mechanics

### ISSUE THREAD

**Issue by DreamingJohnny** [smeas/Beer-and-Plunder#117]
**Description**
It is possible to repair damaged or broken tables. This refills the tables health bar, but does not affect the taverns health at all.

**Subtasks**
- [x] Make it possible to repair damaged and or broken tables.
- [x] Make it cost money to repair tables.
- [x] Repairing a table requires the player to equip the hammer.
- [x] Make a place where the hammers spawn.
- [x] Make repairing a table an action that takes time to perform.
