### ISSUE TITLE
Refilling beer barrels

### ISSUE THREAD

**Issue by DreamingJohnny** [smeas/Beer-and-Plunder#120]
**Description**
Every beer barrel contains a certain amount of beers, after which it needs to be switched. Switching a beer barrel requiers going and getting a new one from some place.

**Subtasks**
- [x] Make it so that the beer tap gives a certain number of beers, after which it is empty and needs to be refilled.
- [x] Make it possible to refill the beer tap.
- [x] Make an object "the beer barrel" that the player avatar needs to get and carry to refill beer.
- [ ] Make the player avatar walk slower when carrying the beer barrel.
- [x] Make it visible for the player when the beer barrel is almost empty.
- [x] Make a spot where the player is able to go and get new barrels of beer.
- [x] Make it impossible to go and get a new barrel of beer before the old one is empty.
