### ISSUE TITLE
Make on additional type of beer (mead for example)

### ISSUE THREAD

**Issue by DreamingJohnny** [smeas/Beer-and-Plunder#121]
**Description**
Make another kind of beer that the Vikings can want.

**Subtasks**
- [ ] Make an additional desire state for it.
- [ ] Make a ikon that shows that this is what the vikings want.
- [ ] Make an additional beer tap for it.
- [ ] Make a barrel for the extra beer-type that you can pick up and go and get.

**Comment by DreamingJohnny** [comment]
So, we should close this issue right? Seeing as we decided that this isn't even something that should be get put on wishlist, but instead was outside of our scope.

**Comment by smeas** [comment]
Closing this as we've decided to only have one type of beer.
