### ISSUE TITLE
Drop coins based on mood

### ISSUE THREAD

**Issue by MrJackey** [smeas/Beer-and-Plunder#122]
**Description**
Vikings should wait a bit before dropping coins

**Subtasks**
- [x] Vikings drop coins with a short delay when fulfilling a desire
- [x] Vikings drop coins when all their desires are fulfilled.
- [x] The value/amount of coins dropped is based on mood

**Additional context**
We want to test both the first and second task to see which one we like the most. Maybe use both??
