### ISSUE TITLE
Fixed amount of reusable tankards

### ISSUE THREAD

**Issue by smeas** [smeas/Beer-and-Plunder#149]
**Description**
There will be a fixed amount of tankards in the tavern that will need to be reused.

**Subtasks**
- [ ] Fixed amount of tankards that exist in the level from the start
- [x] Need to hold a tankard to fill it at the beer tap
- [x] Vikings throw tankard on the floor when done drinking
