### ISSUE TITLE
Set up a play-able tutorial.

### ISSUE THREAD

**Issue by DreamingJohnny** [smeas/Beer-and-Plunder#150]
**Description**
Set up a play-able tutorial that teaches the player the different parts of the game. The tutorial is largely scripted. Step-by-step guiding their way through each of the tasks that we have designed.

**Subtasks**
- [ ] You are able to select the tutorial from the Main Menu.
- [x] The tutorial shows you how to greets guests and guide them to their seat.
- [x] How to pour up a beer
- [x] Serve the beer
- [x] Switch beer barrel when it runs out
- [x] Play the instrument
- [x] Pick up money
- [x] Attack with the axe
- [x] Repair the table
