### ISSUE TITLE
Try to improve the following camera

### ISSUE THREAD

**Issue by smeas** [smeas/Beer-and-Plunder#153]
**Description**
Players like the following camera but they need to be able to get a better overview of the tavern. Some players also feel like the camera is moving a bit too much and get dizzy.

**Subtasks**
- [x] Target vikings as well?
- [x] Bounding box around the tavern?
- [ ] Try to make the camera move a bit less?
