### ISSUE TITLE
Improve the lobby screen

### ISSUE THREAD

**Issue by smeas** [smeas/Beer-and-Plunder#154]
**Description**
The lobby menu needs to be improved. Players are confused about which card is theirs and wether or not they have joined.

**Subtasks**
- [x] Flash the players card when they press a button
- [x] Maybe tint the cards with the player color? (Should player actually be color coded)
- [x] Maybe show an icon of what input device the player is using (keyboard/gamepad)
- [x] Have a way to un-join a device?
- [x] Don't start the game when joining with the start button
