### ISSUE TITLE
Kitchen

### ISSUE THREAD

**Issue by MrJackey** [smeas/Beer-and-Plunder#157]
**Description**
You can give the kitchen a ticket which cooks a meal.
This meal can be delivered to a desiring viking.

**Subtasks**
- [ ] There is a new pickup (ticket)
- [ ] There is a new pickup (food)
- [ ] The kitchen can receive a ticket to start cooking food which takes time
- [ ] No player is required near the kitchen for food to be cooked
- [ ] The food can be given to vikings
