### ISSUE TITLE
Implement Vikings

### ISSUE THREAD

**Issue by MrJackey** [smeas/Beer-and-Plunder#16]
**Description**
Create a basic implementation of vikings

**Subtasks**
- [x] Spawn vikings on specified locations
- [x] Vikings have desires to be met
- [x] Vikings disappear when desires fully met
- [x] Vikings have a "mood" meter
