### ISSUE TITLE
Further sounds to find

### ISSUE THREAD

**Issue by DreamingJohnny** [smeas/Beer-and-Plunder#182]
**Description**
Other sounds that we should preferably have to the game, but that we don't have time to add right now.

**Subtasks**
- [x] Tankard hitting the floor
- [ ] Viking entering the tavern (male & female)
- [ ] Viking acknowledging that you are leading them to a table (male & female). 
- [ ] Viking grunting when throwing tankard (male & female).
- [ ] Happy Viking leaving the bar (male & female)
- [ ] Beaten Viking leaving the bar (male & female)
- [x] "Beep" per second during the last ten seconds of the round.
- [ ] For every hundred cash the players have earned.
- [x] Sound of evil goblin being beaten or thwarted by player, (angry protest, complaining etc.)
- [x] Smoke poof (for when things appear/disappear)
- [x] Kitchen working
