### ISSUE TITLE
Particle Effects - various

### ISSUE THREAD

**Issue by tzaarela** [smeas/Beer-and-Plunder#196]
**Description**
Create some various particle effects

**Subtasks**
- [ ] Dust effect when placing items
- [x] Stunned Effect
- [x] Axe-hit effect
- [x] Instrument effect when playing
- [x] Fire halo from the wall scones on either side of the entrance and exit.
- [x] Fireflies dancing over the grass outside of the tavern.
- [x] Some slight steam coming from the kitchen window.
- [ ] etc

**Comment by DreamingJohnny** [comment]
Added these three sub-tasks to the issue
- [ ] Fire halo from the wall scones on either side of the entrance and exit.
- [ ] Fireflies dancing over the grass outside of the tavern.
- [ ] Some slight steam coming from the kitchen window.
