### ISSUE TITLE
Mood decline visualization

### ISSUE THREAD

**Issue by tzaarela** [smeas/Beer-and-Plunder#197]
**Description**
Make an icon system for show mood status and declining/increasing

**Subtasks**
- [ ] Show current mood status
- [ ] Show mood declining
- [ ] Show mood increasing
