### ISSUE TITLE
UI - Menus and in-game HUD

### ISSUE THREAD

**Issue by denalice00** [smeas/Beer-and-Plunder#201]
**Description**
Design a button in 2D to be used in the different Menus. It must be able to nine-slice. Make 3D sculpture of runestone which should be UV-mapped and texurized. 

**Subtasks**
- [x] Make Basic Button
- [x] Runestone
- [x] Volume slider
- [x] Money count
- [x] Time remaining - clock
- [x] Loading Bars
- [x] Lose screen
- [x] A little bit of text for Win Screen

**Additional context**
This should take a maximum of 2-3 days. Make sure to make a Highpoly, lowpoly and to uv map the menu runestone to finish it.
