### ISSUE TITLE
How tables and tankards are handled when the round is over.

### ISSUE THREAD

**Issue by DreamingJohnny** [smeas/Beer-and-Plunder#202]
**Description**
Tables and tankards aren't repaired, or reset, between rounds, instead. tables damage remains the same, and tankards are places empty on the table close to the viking who was drinking it when the round ended.

**Subtasks**
- [ ] Tables aren't repaired between rounds.
- [ ] Tankards that are being drunk from when the round ends begins the next round empty
- [ ] and on the floor close to where the viking sat.
