### ISSUE TITLE
Uvmap - Interior

### ISSUE THREAD

**Issue by noobLinda** [smeas/Beer-and-Plunder#206]
**Description**
Uvmap Interior objects in Houdini
Set Pivot and Scale before Exporting FBX
Don't forget to add a attributes delete node

**Subtasks**
- [x] Bar Counter
- [x] Instrument Area (Scene, Placeholders for instrument)
- [x] Hammer Area (Anvil, Tools)
- [x] Axe Area (Statue)

**Additional context**
This task is complete when each subtask is exported and tested in Substance
Should take 2-3 days to complete
