### ISSUE TITLE
Texture - Interior

### ISSUE THREAD

**Issue by noobLinda** [smeas/Beer-and-Plunder#208]
**Description**
Texture each subject in Substance
Bake highmesh when necessary
Export Texture

**Subtasks**
- [x] Bar Counter
- [x] Instrument Area (Scene, Placeholders for instrument)
- [x] Hammer Area (Anvil, Tools)
- [x] Axe Area (Statue)

**Additional context**
When all subtasks is completed
import to Unity and assign/test in our ArtTest Scene
