### ISSUE TITLE
Implement thieving goblin

### ISSUE THREAD

**Issue by DreamingJohnny** [smeas/Beer-and-Plunder#212]
**Description**
Implement the thieving goblin that steels coins from the floor.

**Subtasks**
**The goblin should**
- [x] Be able to sense if there are coins on the floor
- [x] Vacuum up coins from the floor close to them.
- [x] Be affected by the player swinging their axe, avoiding it, running from it or disappearing in a puff of smoke when hit?
- [x] Having some way of moving, probably not being affected by the bodies of other guests, tables etc.
- [x] Having spawn spots, probably along the walls that they run inbetween.
