### ISSUE TITLE
Model - Kitchen

### ISSUE THREAD

**Issue by noobLinda** [smeas/Beer-and-Plunder#214]
**Description**
Model what we need for the Kitchen task

**Subtasks**
- [x] Model Kitchens Window (Use old wall model)
- [x] Add sign "Kitchen"
- [x] Create Low and HighPoly mesh
- [x] Model Meat (Only lowpoly)
- [x] Model Food Ticket

**Additional context**
This task should take 1-2 days to complete
