### ISSUE TITLE
Background

### ISSUE THREAD

**Issue by noobLinda** [smeas/Beer-and-Plunder#255]
**Description**
Create what's outside the bar!
Create seamless grass in 2D around the house, fade to black/darkblue on outer edges
Use Kristinas Evergreen tree

**Subtasks**
- [x] Create 2D Seamless Grass, make one or two with variation
- [x] Import Kristinas Evergreen Tree to Unity with textures
- [x] Set scene
- [x] Can we juice it with fireflies/glow?
- [x] Get help from Max on how to achieve the look we want for the grass 
- [x] Import 3D Grass with textures

**Additional context**
Create and test in Unity as you go
Don't forget to create the fade to black/darkblue edges
