### ISSUE TITLE
Improve tutorial

### ISSUE THREAD

**Issue by DreamingJohnny** [smeas/Beer-and-Plunder#259]
**Description**
Improve, update & beautify the tutorial for the game.

**Subtasks**
- [ ] Update with the new stations & minigames
- [ ] Rewrite instructions for clarity
- [ ] Rich colored certain key works
- [ ] Improve highlight on objects
- [ ] Import more beautiful word-bubbles from artists
- [ ] Make sure that the pause screen has been added to the tutorial
