### ISSUE TITLE
Boost mood on desire fulfillment

### ISSUE THREAD

**Issue by MrJackey** [smeas/Beer-and-Plunder#260]
**Description**
When a desire is fulfilled or order is taken boost the vikings mood. 

**Subtasks**
- [x] You can boost a vikings mood clamped to the start value.
- [x] Mood is boosted on desire fulfilled
- [x] Mood is boosted on order taken
