### ISSUE TITLE
Improve re-set between rounds

### ISSUE THREAD

**Issue by DreamingJohnny** [smeas/Beer-and-Plunder#261]
**Description**
Make it so that all loose lying coins, tickets and food disappears between each round. Make sure that the kitchen doesn't continue cooking, or remembers anything from the round before etc.

**Subtasks**
- [ ] Coins that aren't picked up disappears at the start of a new round.
- [ ] Tickets & food disappears between rounds.
- [ ] Kitchen stops cooking food, and any progress on cooking meals are lost, as is any waiting orders etc.
- [ ] Scale to zero over time when disappearing
- [ ] Turn of highlights over pick ups etc while between rounds.

**Comment by DreamingJohnny** [comment]
I removed the issue with the goblin, my understanding is that Jonatan is looking into that already. However I'm adding that highlight visuals should be turned of between rounds, so that the visual effects doesn't intrude.
