### ISSUE TITLE
Animation quirks

### ISSUE THREAD

**Issue by MrJackey** [smeas/Beer-and-Plunder#286]
**Description**
With the newest addition of animations I found some quirks

**Subtasks**
- [x] Vikings can stop and punch when they are too far from table
- [x] Vikings can punch in the air if the table they are seated at becomes destroyed
- [x] Satisfied vikings throwing the given item teleports the item. (Removing the teleport causes the item to be dropped straight down)
- [x] Hitting a viking currently dismounting a chair causes the viking to snap to dismount position when done
