### ISSUE TITLE
Specific itemslots will only accept certain items.

### ISSUE THREAD

**Issue by DreamingJohnny** [smeas/Beer-and-Plunder#287]
**Description**
The item slots in the hammer-, weapon- & scene-stations should only accept to hold the items of it's own kind. While the bar counter should be able to hold all of the different kinds of items.

**Subtasks**
- [ ] See to it that only the hammer can be placed on the Hammerlog in the HammerStation.
- [ ] See so the hammer is oriented standing upside down on its' log
- [ ] Only harp may be placed in the Stand on the InstrumentScene.
- [ ] The harp should be oriented with the same rotation as the Stand has.
- [ ] Only the axe should be placed in the WeaponStand.
- [ ] The axe should take its' placement and rotation from the hands of the WeaponStatue.
- [ ] The bar counter should accept every kind of items.
- [ ] The harp should be lying down when placed on the counter.
- [ ] The item slots on the two barrels should be able to accept items without them clipping in an ugly way.

**Comment by DreamingJohnny** [comment]
This wasn't something that we decided, but I think that the axe and the hammer should also be lying down if you place them on the bar counter.
