### ISSUE TITLE
Set up basic RoundController

### ISSUE THREAD

**Issue by DreamingJohnny** [smeas/Beer-and-Plunder#29]
**Description**
System that checks the time of a "round" of gameplay, starts and ends a round, sets gamestate on "game over", "victory" etc.
Send info about waves of vikings on to VikingManager depending on difficulty etc.

**Subtasks**
- [x] Sends object containing data to VikingManager for each wave.
- [x] Creates objects storing data for each wave of Vikings.
- [ ] Sets gamestate to game over/win etc.
