### ISSUE TITLE
Another tutorial issue

### ISSUE THREAD

**Issue by DreamingJohnny** [smeas/Beer-and-Plunder#299]
**Description**
Fix certain problems that we've noticed in the tutorial.

**Subtasks**
- [x] Fix the viking that refuses to disappear at the end of the tutorial
- [x] Fix rich-ify certain parts of the text in the tutorial.
- [x] Add symbols for controls side by side with the text.
- [x] Add particle effects on items appearing in the tutorial.
- [x] Add a new font to the tutorial text box
- [x] Make certain phases require input to proceed
