### ISSUE TITLE
Menu feedback

### ISSUE THREAD

**Issue by MrJackey** [smeas/Beer-and-Plunder#319]
**Description**
Give the player feedback when navigating a menu

**Subtasks**
- [x] Show initial selection
- [x] Show which element is highlighted
- [x] Add effect on hover
- [ ] Sound effect on click?
