### ISSUE TITLE
Set starting positions for items in tavern

### ISSUE THREAD

**Issue by DreamingJohnny** [smeas/Beer-and-Plunder#32]
**Description**
Set up so tavern begins by filling the starting positions for each of the items. Harps, axes, beer barrels etc.

**Subtasks**
- [ ] Set up references to the various spawn points for the different items.
- [ ] Set up a prefab of the spawn points.
- [ ] Create the various items at each of the places at Start.
