### ISSUE TITLE
Main Character Models

### ISSUE THREAD

**Issue by denalice00** [smeas/Beer-and-Plunder#36]
**Description**
Sculpt a base for the characters and model the four main characters. Also Retopo them.

**Subtasks**
- [x] Nr 1 (Ron Swansson)
- [x]  Nr 2 (Flätor kvinnan)
- [x]  Nr 3 (Mannen m. dryckeshorn)
- [x]  Nr 4 (Damen m. örhängen)  

**Additional context**
Make the main characters and guests in Zbrush - model them from the concept sketches available and retopologize them
