### ISSUE TITLE
Allow guiding vikings to tables

### ISSUE THREAD

**Issue by smeas** [smeas/Beer-and-Plunder#38]
**Description**
The player should be able to tell the vikings where to sit. The vikings should then navigate (or teleport for now) to a chair at that table.

**Subtasks**
- [x] Viking should have a "waiting in line" state
- [x] Can interact with viking to tell them where to sit
- [x] Viking can navigate to the table
