### ISSUE TITLE
Score card && UI between rounds, handled by RoundController

### ISSUE THREAD

**Issue by DreamingJohnny** [smeas/Beer-and-Plunder#45]
**Description**
When the RoundTimer is up the RoundController will enable a UI, pause game, and wait for input from all players before letting next round start.

**Subtasks**
- [ ] Creates UI elements and function for enabling/disabling it, handled by RoundController
- [ ] Pauses game while in menu.
- [ ] Starts new round after getting input.
