### ISSUE TITLE
Juice etc for ScoreCard menu

### ISSUE THREAD

**Issue by DreamingJohnny** [smeas/Beer-and-Plunder#46]
**Description**
Additional juice and some functionality for between-rounds-menu

**Subtasks**
- [ ] Asks for, and shows, some sort of scoring.
- [x] Waits for input from all players before going to next round.
- [ ] Animate parts of the UI.
- [ ] Changes music while in ScoreCard menu.
