### ISSUE TITLE
Create Style Guide

### ISSUE THREAD

**Issue by denalice00** [smeas/Beer-and-Plunder#5]
**Description**
Look at the references and moodboards and create a Style Guide for the game together.
Sketch other sketches and concepts after creating the style guide.

**Subtasks**
- [x] Decide the "don't's"
- [x] Decide the "do's"
- [x] Make color theme

**Additional context**
Think about shapes, a general color theme and  perhaps even what kind of lighting we want to use. Discuss all of these things and choose what kind of "feeling" along with the general vibe we want to give the game. Give the programmers a chance to give input on this topic.
