### ISSUE TITLE
Set up basic brawl system

### ISSUE THREAD

**Issue by DreamingJohnny** [smeas/Beer-and-Plunder#52]
**Description**
Set up the basic viking brawl system.

**Subtasks**
- [x] Vikings enter brawl state when reaching below a threshold
- [x] Vikings can leave the brawl state when a condition is met
- [x] There is an indicator to when a viking is brawling
- [x] The brawling spreads to nearby tables
- [ ] Entering a brawl causes damage to the tavern
