### ISSUE TITLE
Viking leaving state

### ISSUE THREAD

**Issue by MrJackey** [smeas/Beer-and-Plunder#55]
**Description**
The vikings need a state for when they are leaving the tavern

**Subtasks**
- [x] There is a leaving state which makes the viking leave the tavern
- [x] The state is entered when all desires are met
- [x] The state is entered  when a round is over
- [x] The viking disappears when they have left the tavern
