### ISSUE TITLE
Model Viking Guests

### ISSUE THREAD

**Issue by noobLinda** [smeas/Beer-and-Plunder#61]
**Description**
Create 3D models of the guests using the base body and concept sketches

**Subtasks**
- [x] Create the Base Body for all the characters
- [x] Guest 1 Big Horns
- [x] Guest 2 Old Dude
- [x] Guest 3 Viking Lord
- [x] Guest 4 Kind Viking
- [x] Guest 5 Shieldmaiden

**Additional context**
Each character is done when a high poly and low poly version is done
Each character should take up to 2 days to complete
Base Body should take max 1 day to create
