### ISSUE TITLE
Model - Interior

### ISSUE THREAD

**Issue by denalice00** [smeas/Beer-and-Plunder#65]
**Description**
Model the decorations/objects in Zbrush
Create what you can with only Lowpoly (Small Things)
Larger things, like the Bar Counter, Should have a highpoly mesh to bake

**Subtasks**
- [x] Bar Counter
- [x] Instrument Area (Scene, Placeholders for instrument)
- [x] Hammer Area (Anvil, Tools)
- [x] Axe Area (Statue)

**Additional context**
Try to plan each subtask, do you have a already created asset you can reuse here?
Use Lindas and Alices Concept Art as a reference when modeling.
