### ISSUE TITLE
Highscore

### ISSUE THREAD

**Issue by DreamingJohnny** [smeas/Beer-and-Plunder#67]
**Description**
A description of the task.

**Subtasks**
- [ ] Some sort of score mechanic
- [ ] That keeps track of various values
- [ ] Displaying the score per round on the scorecard
