### ISSUE TITLE
Uvmapping Characters

### ISSUE THREAD

**Issue by noobLinda** [smeas/Beer-and-Plunder#68]
**Description**
Use Houdini to create Uvmaps of each character

Before exporting the FBX:
(Do this after Uvmapping is complete)
check scale and pivot on each character
add a attribute delete node

**Subtasks**
- [x] Uvmap Ron Swanson
- [x] Uvmap Kvinna med Flätor
- [x] Uvmap Snubben med Maghorn
- [x] Uvmap Damen med Örhängen

**Additional context**
This task is complete after each uvmap is tested and works in substance
Each character should take up to 1 day to complete
