### ISSUE TITLE
Inworld scorecard menu

### ISSUE THREAD

**Issue by MrJackey** [smeas/Beer-and-Plunder#69]
**Description**
The scorecard menu is in world

**Subtasks**
- [x] The camera zooms in on a location (e.g the bar)
- [x] The players are lined up
- [ ] The score is presented on an inworld object
