### ISSUE TITLE
Connect table health to the tavern health

### ISSUE THREAD

**Issue by DreamingJohnny** [smeas/Beer-and-Plunder#90]
**Description**
Make it so that the health of the tavern and the tables are connected and are set based on the same values.

**Subtasks**
- [ ] The tables damage also be applied to the taverns health.
- [ ] The repair action on the tables also repair the taverns health.
- [ ] The tables health are set based on the taverns health
- [ ] The taverns health is set based on the difficulty
