### ISSUE TITLE
Implementing a Game Over screen.

### ISSUE THREAD

**Issue by DreamingJohnny** [smeas/Beer-and-Plunder#93]
**Description**
A Game Over-screen that shows up if you've lost.

**Subtasks**
- [ ] The screen specifies why you lost (i.e. did you go bankrupt? Was the tavern destroyed?)
- [ ] Button that takes you back to Main Menu.
- [ ] Button that let's your restart the game.
