### ISSUE TITLE
Reset tavern at round start

### ISSUE THREAD

**Issue by MrJackey** [smeas/Beer-and-Plunder#98]
**Description**
Pickups are persistent between rounds, every round should be a clean slate

**Subtasks**
- [x] All "non-player spawned" pickups are returned to their original position
- [x] All "player spawned" pickups are removed from the tavern
- [x] Players are reset to an initial state not carrying anything
